title: Andrew Yantos
author: Andrew Yantos
email: andrewyantos@gmail.com
description: >
  My programming portfolio website. Demonstrating ability with C++, C#, WPF and Computer Graphics technologies.

# social links
social:
  github:  Andidy
  linkedin: andrew-yantos

show_excerpts: true # set to false to remove excerpts on the homepage

collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true

remote_theme: hydecorp/hydejack@v9.1.4
plugins:
  - jekyll-include-cache
