title: Andrew Yantos
author: Andrew Yantos
    github:  Andidy
    linkedin: andrew-yantos
    email: andrewyantos@gmail.com

  description: >
    My programming portfolio and blog site. Demonstrating ability with C++, C#, WPF and Computer Graphics technologies.

  about: |
    I'm Andrew Yantos, an aspiring software engineer currently focusing my efforts on projects that interest me, namely, budgeting and game development.

  

show_excerpts: true # set to false to remove excerpts on the homepage

collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true

remote_theme: hydecorp/hydejack@v9.1.4
plugins:
  - jekyll-include-cache
